
/* Drop Tables */
DROP TABLE SCRAP CASCADE CONSTRAINTS;
DROP TABLE PURCHASE CASCADE CONSTRAINTS;
DROP TABLE CAR CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;


/* Drop Sequences */
DROP SEQUENCE SEQ_CAR_CAR_ID;
DROP SEQUENCE SEQ_CAR_CID;
DROP SEQUENCE SEQ_Customer_CID;
DROP SEQUENCE SEQ_Customer_CUS_ID;
DROP SEQUENCE SEQ_PURCHASE_SID;



/* Create Sequences */

CREATE SEQUENCE SEQ_CAR_CAR_ID NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CAR_CID NOCACHE NOCYCLE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_Customer_CID NOCACHE NOCYCLE  INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_Customer_CUS_ID NOCACHE NOCYCLE  INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PURCHASE_SID NOCACHE NOCYCLE  INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE CAR
(
	-- 차량식별자
	CAR_ID number NOT NULL,
	-- 차명
	CNAME nvarchar2(20) NOT NULL,
	CKIND nvarchar2(20) NOT NULL,
	PRIMARY KEY (CAR_ID)
);


CREATE TABLE Customer
(
	-- 고객식별자
	CUS_ID number NOT NULL,
	-- 고객 이름
	NAME nvarchar2(10) NOT NULL,
	-- 주민번호
	RNUM nvarchar2(14) NOT NULL,
	PHONE nvarchar2(15) NOT NULL,
	-- 가입일
	REGIDATE date DEFAULT SYSDATE,
	PRIMARY KEY (CUS_ID)
);


CREATE TABLE PURCHASE
(
	-- 판매 식별정보
	SID number NOT NULL,
	-- 고객식별자
	CUS_ID number NOT NULL,
	-- 차량식별자
	CAR_ID number NOT NULL,
	PRIMARY KEY (SID)
);


CREATE TABLE SCRAP
(
	-- 폐차식별자
	SC_ID number NOT NULL,
	-- 판매 식별정보
	SID number NOT NULL,
	PRIMARY KEY (SC_ID)
);



/* Create Foreign Keys */

ALTER TABLE PURCHASE
	ADD FOREIGN KEY (CAR_ID)
	REFERENCES CAR (CAR_ID)
;


ALTER TABLE PURCHASE
	ADD FOREIGN KEY (CUS_ID)
	REFERENCES Customer (CUS_ID)
;


ALTER TABLE SCRAP
	ADD FOREIGN KEY (SID)
	REFERENCES PURCHASE (SID)
;



